### ISSUE TITLE
Is it possible to support l4d2?

### ISSUE THREAD

**Issue by 3918831** [YaLTeR/SourcePauseTool#56] opened 2018-11-04 17:16 UTC
Is it possible to support l4d2?Need it a lot...

**Comment by YaLTeR** [comment] 2018-11-04 17:19
cc @mikesmiffy128

**Comment by mikesmiffy128** [comment] 2018-11-04 19:20
The most work I've done regarding L4D2 plugin stuff is an autojump prototype that only works on Linux, and I'm unlikely to further develop / release it any time soon because people are concerned it would make cheating on the RTA leaderboards way easier (right now there's a "bhop script" category which uses a SourceMod-based plugin which is really easy to discern because there's no prediction and it's all horrible and laggy). I don't think anyone else who's been involved in SPT (Jukspa in particular) has been massively interested in L4D2, so unfortunately you'll probably have a long wait ahead of you @3918831. I actually would like to get full TAS support working on L4D2 some time in the distant future but it's a pretty big project, not exactly something you can just make in a day.

That said if you have any specific features including or aside from autojump that you'd like to see developed, let me know - although they'll still be *really* far down the to-do list.

**Comment by 3918831** [comment] 2018-11-05 15:38
Thank a lot for your reply, if it is difficult to do this, then ignore it for now. I am a tas speedrunner player on l4d2 , however the t4d2 tas is just using host_timescale 0.x command, other operations are manual,witch means if you failed,you need to respawn the player for another round,it is a little awkward. I found a plugin I wanted called SourceToolAssist, witch met my needs, but it was done for CSGO. Anyway, thank you very much for your reply, good luck ^_^.

**Comment by 3918831** [comment] 2018-11-05 15:42
Thank a lot for your reply, if it is difficult to do this, then ignore it for now. I am a tas speedrunner player on l4d2 , however the t4d2 tas is just using host_timescale 0.x command, other operations are manual,which means if you failed,you need to respawn the player for another round,it is a little awkward. But I never upload my tas record to RTA, promise, and I found a plugin I wanted called SourceToolAssist, which met my needs, but it was done for CSGO. Anyway, thank you very much for your reply, good luck ^_^.

**Comment by mikesmiffy128** [comment] 2018-11-05 21:57
Yeah, I'm familiar with L4D2 TASing and its limitations, so improving it is something I'd like to do but - again - it's a long term project for a rainy day. Good luck with your runs, anyway.

**Comment by Margen67** [comment] 2019-07-27 03:19
Duplicate of #14

**Closed** 2023-05-03 20:26 UTC
