### ISSUE TITLE
y_spt_autojump "1" causes Portal to crash while leaving a portal.

### ISSUE THREAD

**Issue by 0x2480** [YaLTeR/SourcePauseTool#132] opened 2020-05-29 00:06 UTC

**Comment by InputEvelution** [comment] 2020-05-29 00:33
Is this a duplicate of issue #36? It certainly might help to work out what the problem is, if so.

**Comment by InputEvelution** [comment] 2020-05-29 06:37
Can you provide any details about what version of the game you were using @TERRAERROR, and send us a save from which we could attempt to replicate the glitch?

**Closed** 2023-05-03 20:28 UTC
